//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amark
    {
        public int Sid { get; set; }
        public int AssignmentNumber { get; set; }
        public string Amarks { get; set; }
        public int Mid { get; set; }
    }
}
