//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int Aid { get; set; }
        public int Tid { get; set; }
        public int AssignmentNumber { get; set; }
        public string Title { get; set; }
        public string QuestionText { get; set; }
        public System.DateTime Deadline { get; set; }
        public string DatabaseName { get; set; }
        public string Section { get; set; }
        public int Smester { get; set; }
        public string assignFile { get; set; }
        public int totalMarks { get; set; }
    }
}
