//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentSolution
    {
        public int Sloid { get; set; }
        public int AssignmentNumber { get; set; }
        public string Solution { get; set; }
        public int Smester { get; set; }
        public string Section { get; set; }
    }
}
