//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solution
    {
        public int SolutionId { get; set; }
        public Nullable<int> AssignmentNumber { get; set; }
        public string SolutionFilePath { get; set; }
        public Nullable<int> Semester { get; set; }
        public string Section { get; set; }
    }
}
