//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Sid { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Semester { get; set; }
        public string Section { get; set; }
        public string Semail { get; set; }
        public string Spassword { get; set; }
    }
}
