//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int Tid { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Temail { get; set; }
        public string Tpassword { get; set; }
    }
}
